# Generated by Django 3.0.7 on 2022-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20220127_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reg',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
